### ISSUE TITLE
Signature verification doesn't work on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#183]
```
Resolving dependencies for com.atomist:rug (1.0.0-m.1·jar) failed
com.atomist.rug.cli.RunnerException: org.bouncycastle.util.Strings.newList()Lorg/bouncycastle/util/StringList;
    at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:29)
    at com.atomist.rug.cli.command.ReflectiveCommandRunner.loadArtifactAndinitializeEnvironment(ReflectiveCommandRunner.java:114)
    at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:56)
    at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
    at com.atomist.rug.cli.Runner.run(Runner.java:40)
    at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
    at com.atomist.rug.cli.Main.main(Main.java:25)
Caused by: java.lang.NoSuchMethodError: org.bouncycastle.util.Strings.newList()Lorg/bouncycastle/util/StringList;
    at org.bouncycastle.bcpg.ArmoredInputStream.<init>(Unknown Source)
    at org.bouncycastle.bcpg.ArmoredInputStream.<init>(Unknown Source)
    at org.bouncycastle.openpgp.PGPUtil.getDecoderStream(Unknown Source)
    at com.atomist.rug.resolver.GpgSignatureVerifier.<init>(GpgSignatureVerifier.java:35)
    at com.atomist.rug.resolver.GpgSignatureVerifier.<init>(GpgSignatureVerifier.java:29)
    at com.atomist.rug.cli.resolver.DependencyResolverFactory.verifiers(DependencyResolverFactory.java:45)
    at com.atomist.rug.cli.command.ReflectiveCommandRunner.resolveDependencies(ReflectiveCommandRunner.java:208)
    at com.atomist.rug.cli.command.ShellCommandRunner.resolveDependencies(ShellCommandRunner.java:52)
    at com.atomist.rug.cli.command.ReflectiveCommandRunner.lambda$loadArtifactAndinitializeEnvironment$0(ReflectiveCommandRunner.java:118)
    at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:22)
    ... 6 more
```

**Comment by cdupuis** [comment]
Reported in https://atomist-community.slack.com/archives/C29FP383X/p1493501344533909

**Comment by cdupuis** [comment]
I'm pretty sure bouncycastle is coming in from some other class loader in this setup. I will have to investigate.

**Comment by cdupuis** [comment]
I just tried on a new install on said Ubuntu and didn't see this error. I wonder what could cause this. Needs further investigation.

**Comment by dandew** [comment]
FWW since verification has been added, none of my users, who are on MacOS and Debian, have been able to use our internally published rugs without the `--disable-verification`. We're unsure if it's an issue that comes when we publish rugs (wrong signature?) or when we pull them (wrong setup on the clients?).

**Comment by cdupuis** [comment]
@dandew, are you seeing the same `NoSuchMethodError` or is the verification simply failing for you? Could you post the output of the command running with `-X` to this issue?

What we've seen in the past is artifact repositories like jfrog re-writing the pom.xml when you download the artifacts through a virtual repo. Could that be a cause here? Are you directly accessing our repositories or do you have some proxy or virtual repo setup in between?

**Comment by dandew** [comment]
You're correct: it is simply failing and is not related to `NoSuchMethodError`, I realized that after running with `-X` as you suggested:
```
Verifying integrity of com.atomist:rug (0.26.1) failed
Resolving dependencies for XXX:commons-rugs (latest·zip) failed

com.atomist.rug.cli.RunnerException: Verification of com.atomist:rug (0.26.1) failed
at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:29)
at com.atomist.rug.cli.command.ReflectiveCommandRunner.loadArtifactAndinitializeEnvironment(ReflectiveCommandRunner.java:114)
at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:56)
at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
at com.atomist.rug.cli.Runner.run(Runner.java:40)
at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
at com.atomist.rug.cli.Main.main(Main.java:25)
Caused by: com.atomist.rug.cli.command.CommandException: Verification of com.atomist:rug (0.26.1) failed
at com.atomist.rug.cli.command.ReflectiveCommandRunner.resolveDependencies(ReflectiveCommandRunner.java:213)
at com.atomist.rug.cli.command.ShellCommandRunner.resolveDependencies(ShellCommandRunner.java:52)
at com.atomist.rug.cli.command.ReflectiveCommandRunner.lambda$loadArtifactAndinitializeEnvironment$0(ReflectiveCommandRunner.java:118)
at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:22)
... 6 more
```
And you're correct a second time: we are deploying to and proxying via jfrog's Artifactory.

**Comment by cdupuis** [comment]
yeah, there is a setting on the virtual repo to not re-write poms. Not sure why they rewrite by default.

**Comment by dandew** [comment]
no idea either, but we're good as long as no-one removes the `--disable-verification` flag from `rug-cli` 😅

**Comment by cdupuis** [comment]
@dandew, if you're able administer the jfrog instance I'll get that setting for you.

**Comment by dandew** [comment]
thanks but alas, no, these settings are out of reach...

**Comment by cdupuis** [comment]
We decided to provide an option to disable the verification from the settings `cli.yml` file. Hope that helps.

**Comment by dandew** [comment]
thank you so much, it will help indeed 🙇

**Comment by cdupuis** [comment]
@dandew see #187
